branch-defaults:
  default:
    environment: lokiserver-dev
    group_suffix: null
global:
  application_name: lokiserver-dev
  branch: null
  default_ec2_keyname: lokitest
  default_platform: Python 3.4
  default_region: us-west-2
  profile: eb-cli
  repository: null
  sc: null
